packages:
  - 'packages/*'
allowBuilds:
  bcrypt: true
  electron: true
  esbuild: false
  mongodb-memory-server: false
  msgpackr-extract: false
  phantomjs-prebuilt: set this to true or false
  protobufjs: true
  sharp: true
